/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0a0a0a",
        "on-secondary-fixed-variant": "#005321",
        "secondary-fixed-dim": "#fdba74",
        "on-primary-fixed": "#360f00",
        "surface-variant": "#333537",
        "on-background": "#e5e2e1",
        "surface-dim": "#0e0e0e",
        "on-tertiary": "#00344f",
        "secondary-container": "#ea580c",
        "background": "#0e0e0e",
        "primary-container": "#f97316",
        "surface-container-highest": "#333537",
        "on-primary-container": "#591e00",
        "on-tertiary-container": "#003550",
        "on-primary-fixed-variant": "#7d2d00",
        "on-surface-variant": "#a8a29e",
        "inverse-on-surface": "#2f3132",
        "primary-fixed": "#ffdbcd",
        "on-tertiary-fixed-variant": "#004b70",
        "surface-container": "#1a1a1a",
        "secondary-fixed": "#fdba74",
        "on-tertiary-fixed": "#001e30",
        "tertiary-container": "#00a2eb",
        "secondary": "#fdba74",
        "outline-variant": "#44403c",
        "on-error-container": "#ffdad6",
        "surface-tint": "#fdba74",
        "surface-bright": "#37393b",
        "on-secondary-container": "#431400",
        "surface-container-low": "#141414",
        "primary-fixed-dim": "#fdba74",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#cae6ff",
        "on-surface": "#e5e2e1",
        "tertiary-fixed-dim": "#8dcdff",
        "inverse-primary": "#a43e00",
        "on-secondary": "#431400",
        "error": "#ffb4ab",
        "surface-container-high": "#262626",
        "surface": "#0e0e0e",
        "primary": "#fdba74",
        "on-error": "#690005",
        "error-container": "#93000a",
        "tertiary": "#8dcdff",
        "outline": "#78716c",
        "on-primary": "#431400",
        "on-secondary-fixed": "#2a0800",
        "accent": "#ea580c",
        "dark": "#0e0e0e"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "32px",
        "navbar-height": "52px",
        "container-margin": "24px",
        "card-padding-y": "20px",
        "gutter": "16px",
        "card-padding-x": "24px"
      },
      fontFamily: {
        "headline": ["Space Grotesk", "Inter", "sans-serif"],
        "stat-lg": ["Space Grotesk", "Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Space Grotesk", "Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Space Grotesk", "Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Space Grotesk", "Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "stat-lg": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
