/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0c0e10",
        "on-secondary-fixed-variant": "#005321",
        "secondary-fixed-dim": "#4ae176",
        "on-primary-fixed": "#360f00",
        "surface-variant": "#333537",
        "on-background": "#e2e2e4",
        "surface-dim": "#121415",
        "on-tertiary": "#00344f",
        "secondary-container": "#00b954",
        "background": "#0A0A0F",
        "primary-container": "#ff6b1a",
        "surface-container-highest": "#333537",
        "on-primary-container": "#591e00",
        "on-tertiary-container": "#003550",
        "on-primary-fixed-variant": "#7d2d00",
        "on-surface-variant": "#e2bfb2",
        "inverse-on-surface": "#2f3132",
        "primary-fixed": "#ffdbcd",
        "on-tertiary-fixed-variant": "#004b70",
        "surface-container": "#1e2021",
        "secondary-fixed": "#6bff8f",
        "on-tertiary-fixed": "#001e30",
        "tertiary-container": "#00a2eb",
        "secondary": "#4ae176",
        "outline-variant": "#5a4137",
        "on-error-container": "#ffdad6",
        "surface-tint": "#ffb596",
        "surface-bright": "#37393b",
        "on-secondary-container": "#004119",
        "surface-container-low": "#1a1c1d",
        "primary-fixed-dim": "#ffb596",
        "inverse-surface": "#e2e2e4",
        "tertiary-fixed": "#cae6ff",
        "on-surface": "#e2e2e4",
        "tertiary-fixed-dim": "#8dcdff",
        "inverse-primary": "#a43e00",
        "on-secondary": "#003915",
        "error": "#ffb4ab",
        "surface-container-high": "#282a2c",
        "surface": "#121415",
        "primary": "#ffb596",
        "on-error": "#690005",
        "error-container": "#93000a",
        "tertiary": "#8dcdff",
        "outline": "#a98a7e",
        "on-primary": "#581e00",
        "on-secondary-fixed": "#002109"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "32px",
        "navbar-height": "52px",
        "container-margin": "24px",
        "card-padding-y": "20px",
        "gutter": "16px",
        "card-padding-x": "24px"
      },
      fontFamily: {
        "stat-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "stat-lg": ["28px", { "lineHeight": "34px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
